# Copyright (C) 2025 Bayerische Motoren Werke Aktiengesellschaft (BMW AG). All rights reserved.

load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "utils",
    srcs = [
        "logger.py",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "pathlib_utils",
    srcs = ["pathlib_utils.py"],
    visibility = ["//visibility:public"],
)
