# Copyright (C) 2025 Bayerische Motoren Werke Aktiengesellschaft (BMW AG). All rights reserved.

filegroup(
    name = "old_test_data",
    srcs = glob(["*"]),
    visibility = ["//quality_tools/llvm_cov:__subpackages__"],
)

filegroup(
    name = "test_data",
    srcs = ["lcov.dat"],
    visibility = ["//quality_tools/llvm_cov/test:__subpackages__"],
)
