name: Create CodeCoverage
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
    coverage_llvm:
      # Starting with Ubuntu 24.04 apparmor breaks Bazels linux-sandbox: https://github.com/bazelbuild/bazel/issues/24081
      runs-on: ubuntu-22.04
      steps:
        - name: Install xmllint
          run: sudo apt install -y libncurses5
        - name: free
          run: rm -rf /usr/share/dotnet/ ; rm -rf /opt/hostedtoolcache
        - uses: bazel-contrib/setup-bazel@0.15.0
          with:
            bazelisk-cache: true
            disk-cache: ${{ github.workflow }}
            repository-cache: true
        - name: Checkout repository
          uses: actions/checkout@v4.2.2
        - name: Bazel build communication targets
          run: |
            bazel coverage //...
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./bazel-out/_coverage/_coverage_report.dat
            flags: unittests
            fail_ci_if_error: true
            verbose: true
